spring:
  application:
    name: backend-Java-onboarding

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        foremat_sql: true
        use_sql_commnts: true

  datasource:
    url: jdbc:h2:mem:testdb  # 메모리 DB로 설정 (서버에 저장하지 않음)
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console


security:
  jwt:
    token:
      secret-key: asdfasfdasfsafsadfsafassafasfasfasdfsaf3dfdfadf34wt232ds
      expire-length: 3600000  # 만료 시간 (밀리초 단위)
